# http://eslint.org/docs/rules/

root: true
parserOptions:
  ecmaFeatures:
    impliedStrict: true
  ecmaVersion: 2015
env:
  es6: true
  node: true
plugins:
  - prettier
extends:
  - prettier
rules:
  prettier/prettier:
    - 2
    - singleQuote: true
