---

# Contact CTA Footer
# ------------------

contact:
  - title: 'Let’s Talk About Your Web Project'
    susytitle: 'Partner with OddBird on Your Next Project'
    subtitle: 'Give Wings to Your Vision'
    action:
      text: 'Get a free consulation'
      url: '/contact/'
    content: |
      OddBird is a full-stack design and development agency,
      partnering with funded startups and enterprise companies
      to create custom Django web applications.
      No matter your size,
      we’re ready to help take your project from concept to launch.
      Reach out any time:
      inquire about <a href="/work/services/">our services</a>,
      set up a free consultation,
      invite us to <a href="/speaking/">speak at your company or event</a>,
      or just say hello.
      <a href="/birds/#bird-miriam">Miriam Suzanne</a>
      will get back to you soon.


# Navigation
# ----------

nav:
  - text: 'work'
    subnav:
      - text: 'case-studies'
        display_text: 'case studies'
        url: '/work/'
      - text: 'services'
        url: '/work/services/'
  - text: 'open-source'
    display_text: 'open source'
    url: '/open-source/'
  - text: 'blog'
    display_text: 'articles'
    url: '/blog/'
  - text: 'about'
    display_text: 'about us'
    subnav:
      - text: 'birds'
        display_text: 'meet the birds'
        url: '/birds/'
      - text: 'speaking'
        display_text: 'public speaking'
        url: '/speaking/'
      - text: 'community'
        url: '/community/'
      - text: 'contact'
        display_text: 'contact us'
        url: '/contact/'


susy_nav:
  - text: 'susysite-articles'
    display_text: 'articles'
    url: '/susy/articles/'
  - text: 'susysite-support'
    display_text: 'support'
    subnav:
      - text: 'docs'
        display_text: 'reference documentation'
        url: '/susy/docs/'
      - text: 'github'
        display_text: 'github issues'
        url: 'https://github.com/oddbird/susy/issues'
      - text: 'stack-overflow'
        display_text: 'stack overflow'
        url: 'http://stackoverflow.com/questions/tagged/susy-sass'
      - text: 'twitter'
        display_text: 'twitter'
        url: 'http://twitter.com/sasssusy/'
      - text: 'susysite-styleguide'
        display_text: 'brand styleguide'
        url: '/susy/styleguide/'
  - text: 'susysite-sites'
    display_text: 'sites'
    url: '/susy/sites/'
  - text: 'oddbird'
    display_text: 'oddbird'
    url: '/'


# Site Settings
# -------------

copyright: '2009–2017'
email: 'birds@oddbird.net'

location: 'blog'
author: 'oddbird'
comments: false


# rstBlog Setup
# -------------

active_modules: [
  jinja_macros,
  typogrify,
  rst,
  images,
  denormalize_config,
  tags,
  rst,
  blog,
  author,
  pages,
  wrap,
  hashedassets,
  urls
  ]
programs:
  '*.rst': 'rst'
  '*.jpg': 'image'
  '*.jpeg': 'image'
  '*.png': 'image'
canonical_url: http://oddbird.net/
template_path: ../templates
asset_map_path: static/assets.json
rst_writer: html5writer
smart_quotes: true
ignore_files: ['.*', '_*', 'config*.yml', 'Makefile', 'README', '*.conf', '*~']
modules:
  blog:
    index_url: /blog/
    per_page: 10
