---
# Navigation
# ----------
nav:
  - text: home
    url: /
  - text: birds
    url: /birds/
  - text: work
    url: /work/
  - text: blog
    url: /blogtemplate/
  - text: in the community
    url: /community/
  - text: contact
    url: /contact/



# Future Talks
# ------------
talks_future: false


# Past Talks
# ----------
talks_past:
  - title: 'Magic with Sass Maps'
    author: miriam
    date: September 12
    year: 2014
    forum: BlendConf
    forum_url: http://www.blendconf.com/

  - title: 'Getting to know Sass'
    author: claudina
    date: September 11
    year: 2014
    forum: BlendConf
    forum_url: http://www.blendconf.com/

  - title: 'The Post-Obsolete Book'
    author: miriam
    date: June 19
    year: 2014
    forum: ELO Conference
    forum_url: http://conference.eliterature.org/

  - title: 'Sass Bites #37'
    author: claudina
    date: May 13
    year: 2014
    forum: Sass Bites
    forum_url: https://www.youtube.com/user/sassbites
    video: https://www.youtube.com/watch?v=BtWaFDpyDCI

  - title: 'Your Own Damn [Susy] System'
    author: miriam
    date: April 24
    year: 2014
    forum: Bmore Sass
    forum_url: http://bmore-sass.com/
    slides: http://miriamsuzanne.com/pres/susy2/
    video: http://vimeo.com/miriamsuzanne/susy-2-system

  - title: 'Show Your Work <i class="amp">&</i> Share Your Toys'
    author: miriam
    date: April 19th
    year: 2014
    forum: Camp Sass
    forum_url: http://campsass.com/2014/
    slides: http://miriamsuzanne.com/pres/show-yr-work/index.html

  - title: 'Set Your Code Free'
    author: carl
    date: April 13
    year: 2014
    forum: PyCon
    forum_url: https://us.pycon.org/2014/
    slides: http://oddbird.net/set-your-code-free-preso/
    video: http://pyvideo.org/video/2637/set-your-code-free-releasing-and-maintaining-an

  - title: 'Susy Grids 2.0'
    author: miriam
    date: March 13
    year: 2014
    forum: Sass Bites
    forum_url: https://www.youtube.com/user/sassbites
    video: https://www.youtube.com/watch?v=m7k-vBzebPg

  - title: 'Python Testing Tools'
    author: carl
    date: February 28
    year: 2014
    forum: ConFoo
    forum_url: http://confoo.ca/
    slides: http://oddbird.net/python-testing-tools-preso/

  - title: 'Advanced Python'
    author: carl
    date: February 27
    year: 2014
    forum: ConFoo
    forum_url: http://confoo.ca/
    slides: http://oddbird.net/advanced-python-preso/

  - title: 'Organizing Sass Partials'
    author: miriam
    date: November 19
    year: 2013
    forum: NYCSass Meetup
    forum_url: http://www.meetup.com/nyc-sass/events/146898452/
    slides: http://miriamsuzanne.com/pres/sass-partials/

  - title: 'Show Your Work <i class="amp">&</i> Share Your Toys'
    author: miriam
    date: October 12
    year: 2013
    forum: SassConf
    forum_url: http://sassconf.com/2013/
    slides: http://miriamsuzanne.com/pres/show-yr-work/index.html
    video: https://vimeo.com/channels/sassconf2013/86306775

  - title: 'Getting Started with Automated Testing'
    author: carl
    date: March 16
    year: 2013
    forum: PyCon
    forum_url: https://us.pycon.org/2013/
    slides: http://oddbird.net/start-testing-preso/
    video: http://pyvideo.org/video/1674/getting-started-with-automated-testing


# Company
# -------
company:
  - name: OddBird
    bio: |
      thrives on freely shared ideas
      <i class="amp">&</i> playful collaboration,
      crossing disciplines, breaking boundaries,
      and eating our dessert with the soup&nbsp;spoon.
    links:
      - [birds, /birds/]
      - [email, birds(who are 'at' the)oddbird.net]
      - [twitter, oddbird]


# Birds
# -----
birds:
  - name: Carl Meyer
    author: carl
    bio: |
      is a <a href="http://github.com/carljm">coder</a>,
      <a href="http://www.python.org/">Pythonista</a>,
      and <a href="http://djangoproject.com/">Django</a> core developer.
      When he’s not chasing a more elegant algorithm,
      he chases frisbees, hockey pucks, and a pair of&nbsp;sons.
    links:
      - [twitter, carljm]
      - [github, carljm]

  - name: Miriam Suzanne
    author: miriam
    bio: |
      is an artist <span class="amp">&</span> experience designer,
      mixing <a href="http://miriamsuzanne.com">words</a>,
      <a href="http://dribbble.com/miriamsuzanne/">images</a>,
      <a href="http://teacupgorilla.com/">music</a>,
      <a href="http://github.com/mirisuzanne/">code</a>,
      and <a href="http://vicioustrap.com/">performance</a>.
      She's a sucker for new projects, puzzles,
      and postprandial&nbsp;perambulations.
    links:
      - [twitter, mirisuzanne]
      - [github, mirisuzanne]

  - name: Jonny Gerig Meyer
    author: jonny
    bio: |
      is a
      <a href="http://github.com/jgerigmeyer/">front-end developer</a>
      who enjoys writing clean, well-tested JavaScript web applications
      and experimenting with the framework-of-the-month.
      He’s excited about
      <a href="http://untappd.com/brewery/81493">homebrewing</a>,
      <a href="http://www.goshenultimate.com/">ultimate frisbee</a>,
      and trying to keep up with his two-year-old&nbsp;daughter.
    links:
      - [twitter, jgerigmeyer]
      - [github, jgerigmeyer]

  - name: Claudina Sarahe
    author: claudina
    no_posts: True
    bio: |
      is a front-end developer, pattern wrangler, teacher,
      and <a href="http://sassconf.com/">conference&nbsp;organizer</a>.
    links:
      - [twitter, itsmisscs]
      - [github, misscs]

  - name: Sondra E
    author: sondra
    no_posts: True
    bio: |
      is a product designer, writer, entrepreneur,
      and <a href="http://teacupgorilla.com/">musician</a>.
      She likes alliteration,
      awkward conversation,
      and chocolate chip&nbsp;cookies.


# Settings
copyright: 2009–2016
author: OddBird
comments: true
location: blog


# rstBlog Setup
active_modules: [
  pygments_simple,
  tags,
  blog,
  author,
  wrap,
  typogrify,
  hashedassets
  ]
canonical_url: http://oddbird.net/
template_path: ../templates
asset_map_path: static/dist/assets.json
rst_writer: html5writer
ignore_files: ['.*', '_*', 'config*.yml', 'Makefile', 'README', '*.conf', '*~']
modules:
  pygments:
    style: tango
  blog:
    index_url: /blog/
    per_page: 10
