---
active_modules: [pygments, tags, blog, author]
author: OddBird
canonical_url: http://oddbird.net/
output_folder: ../output
template_path: ../templates
modules:
  pygments:
    style: tango
  blog:
    index_url: /blog/
