---
active_modules: [pygments, tags, blog, author, wrap, typogrify, norebuild]
author: OddBird
canonical_url: http://oddbird.net/
output_folder: ../output
template_path: ../templates
rst_writer: html5writer
modules:
  pygments:
    style: tango
  blog:
    index_url: /blog/
