---


# Navigation
# ----------

nav:
  - text: 'work'
    subnav:
      - text: 'case-studies'
        display_text: 'case studies'
        url: '/work/'
      - text: 'services'
        url: '/work/services/'
  - text: 'open-source'
    display_text: 'open source'
    url: '/open-source/'
  - text: 'blog'
    display_text: 'articles'
    url: '/blog/'
  - text: 'about'
    display_text: 'about us'
    subnav:
      - text: 'birds'
        display_text: 'meet the birds'
        url: '/birds/'
      - text: 'speaking'
        display_text: 'public speaking'
        url: '/speaking/'
      - text: 'community'
        url: '/community/'
      - text: 'contact'
        display_text: 'contact us'
        url: '/contact/'


# Site Settings
# -------------

copyright: '2009–2017'
email: 'birds@oddbird.net'

location: 'blog'
author: 'oddbird'
comments: false


# rstBlog Setup
# -------------

active_modules: [
  jinja_macros,
  typogrify,
  rst,
  images,
  denormalize_config,
  tags,
  blog,
  author,
  pages,
  wrap,
  hashedassets,
  urls
  ]
programs:
  '*.rst': 'rst'
  '*.jpg': 'image'
  '*.jpeg': 'image'
  '*.png': 'image'
canonical_url: http://oddbird.net/
template_path: ../templates
asset_map_path: static/assets.json
rst_writer: html5writer
smart_quotes: true
ignore_files: ['.*', '_*', 'config*.yml', 'Makefile', 'README', '*.conf', '*~']
modules:
  blog:
    index_url: /blog/
    per_page: 10
