---
location: blog

company:
  - name: OddBird
    type: org
    email: birds(who are 'at' the)oddbird.net
    twitter: oddestbirds
    bio: |
      thrives on freely shared ideas
      <span class="amp">&</span> playful collaboration,
      crossing disciplines, breaking boundaries,
      and eating our dessert with the soup&nbsp;spoon.


birds:
  - name: Carl Meyer
    twitter: carljm
    github: carljm
    bio: |
      is a <a href="http://github.com/carljm">coder</a>,
      <a href="http://www.python.org/">Pythonista</a>,
      and <a href="http://djangoproject.com/">Django</a> core developer.
      When he’s not chasing a more elegant algorithm,
      he chases frisbees, hockey pucks, and a six-year-old son.

  - name: Eric M Suzanne
    twitter: ericmsuzanne
    github: ericam
    bio: |
      is an artist <span class="amp">&</span> experience designer,
      mixing <a href="http://eric.ericsuzanne.com">words</a>,
      <a href="http://dribbble.com/ericam/">images</a>,
      <a href="http://teacupgorilla.com/">music</a>,
      <a href="http://github.com/ericam/">code</a>,
      and <a href="http://vicioustrap.com/">performance</a>.
      He’s a sucker for new projects, puzzels, and processes.

  - name: Jonny Gerig Meyer
    twitter: jgerigmeyer
    github: jgerigmeyer
    bio: |
      is a
      <a href="http://github.com/jgerigmeyer/">front-end developer</a>,
      ultimate frisbee D-line cutter,
      and occasional
      <a href="http://www.goshen.edu/jonam/">college philosophy professor</a>.
      He likes complicated board games, homebrewed IPAs, and hucking it deep.

  - name: Claudina Sarahe
    twitter: itsmisscs
    github: misscs
    bio: |
      is a front-end developer, pattern wrangler,
      and etc etc.
      She does all sort of cool etc,
      like writing her own damn bio.
      AmIRight?


# Copyright
copyright: 'Copyright © 2009-2014 <b>OddBird</b>'


# rstBlog Setup
active_modules: [
  pygments_simple,
  tags,
  blog,
  author,
  wrap,
  typogrify,
  hashedassets
  ]
author: OddBird
canonical_url: http://oddbird.net/
template_path: ../templates
asset_map_path: static/dist/assets.json
rst_writer: html5writer
ignore_files: ['.*', '_*', 'config*.yml', 'Makefile', 'README', '*.conf', '*~']
modules:
  pygments:
    style: tango
  blog:
    index_url: /blog/
