---

# Future Talks
# ------------
events:

  - venue: 'CSS Summit'
    url: 'http://environmentsforhumans.com/2016/css-summit/'
    date: ['07', '26', '2016']
    talks:
      - title: 'Code Patterns for Pattern-Making'
        author: 'miriam'

  - venue: 'CascadiaFest'
    url: 'http://2016.cascadiafest.org/'
    date: ['08', '03', '2016']
    talks:
      - title: 'Code Patterns for Pattern-Making'
        author: 'miriam'



# Open Source Contributions
# -------------------------

oss:
  - name: 'Susy'
    url: 'http://susy.oddbird.net'
    blog: 'susy'
    tagline: 'Web layout power tools.'
    description: |
      In a world of agile development and super-tablet-multi-magic-laptop-phones,
      the best layouts can’t be contained in a single framework or technique.
      CSS Libraries are a bloated mess of opinions about how to do your job.
      Why let the table-saw tell you where to put the kitchen?
    who:
      - name: 'miriam'
        role: 'creator'

  - name: 'Django'
    url: 'https://www.djangoproject.com/'
    blog: 'django'
    tagline: 'The web framework for perfectionists with deadlines.'
    description: |
      Django is a high-level Python Web framework
      that encourages rapid development and clean, pragmatic design.
      Built by experienced developers,
      it takes care of much of the hassle of Web development,
      so you can focus on writing your app
      without needing to reinvent the wheel.
    who:
      - name: 'carl'
        role: 'core-developer'

  - name: 'True'
    url: 'http://oddbird.net/true'
    blog: 'sass-true'
    tagline: 'Powerful unit-testing for Sass.'
    description: |
      True is a full-featured unit-testing library for Sass developers.
      The core functionality is written in pure SassScript,
      so it can be used anywhere Sass is compiled.
      Advanced features are available in Node
      with our Mocha test-runner integration,
      and in Ruby using our command-line tools.
    who:
      - name: 'miriam'
        role: 'creator'



# Giving
# ------

giving:
  - name: 'Django Girls'
    url: 'https://djangogirls.org/'
    type: 'donations'
    description: |
      is a non-profit organization
      and a community that empowers and helps women to organize free,
      one-day programming workshops by providing tools,
      resources and support.
  - name: 'Black Girls CODE'
    url: 'http://blackgirlscode.com/'
    type: 'donations'
    description: |
      has set out to prove to the world
      that girls of every color have the skills
      to become the programmers of tomorrow.
      By promoting classes and programs
      they help to grow the number of women of color
      working in technology,
      and give underprivileged girls a chance
      to become the masters of their technological worlds.
  - name: 'PyLadies'
    url: 'http://www.pyladies.com/'
    type: 'donations'
    description: |
      is an international mentorship group
      with a focus on helping more women become active participants
      and leaders in the Python open-source community.
  - name: 'SassConf'
    url: 'http://sassconf.com/'
    type: 'sponsorships'
    description: |
      is a yearly event that brings together
      a far-flung community of front-end developers,
      designers, architects, and web enthusiasts
      who dream of building a better web.
      Originally born out of NYC’s GothamSass meetup,
      SassConf has grown from a language-specific conference
      to an event on the cutting edge of front-end technology.
  - name: 'DjangoCon'
    url: 'https://djangocon.us/'
    type: 'sponsorships'
    description: |
      is an international Django-community conference,
      for the community, and by the community.
  - name: 'PyCon'
    url: 'https://us.pycon.org/'
    type: 'sponsorships'
    description: |
      is the largest annual gathering
      for the people who use and develop
      the open-source Python programming language.



# OddBirds
# --------

birds:
  - name: 'Miriam Suzanne'
    author: 'miriam'
    role: 'co-founder and creative director'
    adr:
      city: 'Denver'
      state: 'CO'
    bio: |
      Miriam leads the creative process,
      working with clients and users to organize priorities,
      and find solutions to their unique problems.
      She is a pioneer of modern CSS techniques
      and open-source Sass tools —
      including the popular Susy responsive-grid toolkit,
      and True unit-testing library.
      She is the co-author of
      SitePoint’s Jump Start Sass,
      a well-known speaker at front-end conferences,
      and a multi-media artist
      with extensive experience in theatre,
      writing, music, and visual art.
    oss:
      - name: 'Susy'
        url: 'http://susy.oddbird.net'
        role: 'creator'
      - name: 'True'
        url: 'http://oddbird.net/true'
        role: 'creator'
      - name: 'Accoutrement'
        url: 'http://oddbird.net/accoutrement'
        role: 'creator'
      - name: 'Compass'
        url: 'http://compass-style.org'
        role: 'core developer'
    publications:
      - name: 'Jump Start Sass'
        url: 'https://www.sitepoint.com/premium/books/jump-start-sass'
      - name: 'Riding SideSaddle*'
        url: 'http://ridingsidesaddle.com'
    links:
      - twitter: 'mirisuzanne'
        github: 'mirisuzanne'
        dribbble: 'miriamsuzanne'
        lanyrd: 'miriamsuzanne'
        stackoverflow: '1930386'

  - name: 'Jonny Gerig Meyer'
    author: 'jonny'
    role: 'co-founder and front-end developer'
    adr:
      city: 'Goshen'
      state: 'IN'
    bio: |
      Jonny leads the front-end development process,
      turning your ideas into functional interactions.
      He has been writing clean,
      well-tested JavaScript web applications
      for over seven years.
      He has authored or contributed to
      numerous open-source projects,
      and is an active member in the JavaScript community.
      Jonny also gets excited about homebrewing,
      ultimate frisbee,
      and trying to keep up with his two-year-old daughter.
    links:
      - twitter: 'jgerigmeyer'
        github: 'jgerigmeyer'
        stackoverflow: '854407'

  - name: 'Carl Meyer'
    author: 'carl'
    role: 'co-founder'
    adr:
      city: 'Rapid City'
      state: 'SD'
    bio: |
      Carl is an active owner and developer-emeritus,
      providing regular oversight and counsel
      to the development team.
      He is a core developer of the Django Python web framework,
      an elected member of the inaugural Django technical board,
      maintainer of the widely-used pip and virtualenv
      package management tools,
      co-author of multiple accepted
      enhancements to the Python language and ecosystem,
      and a Fellow of the Python Software Foundation.
      He is also a well-known speaker
      at the annual Python and Django community conferences.
    oss:
      - name: 'Django'
        url: 'https://www.djangoproject.com/'
        role: 'core developer'
      - name: 'pip'
        url: '@@@'
        role: 'maintainer'
      - name: 'virtualenv'
        url: '@@@'
        role: 'maintainer'
    links:
      - twitter: 'carljm'
        github: 'carljm'
        lanyrd: 'carljm'
        stackoverflow: '3207'

  - name: 'Sondra Eby'
    author: 'sondra'
    role: 'user-experience designer'
    adr:
      city: 'Denver'
      state: 'CO'
    no_posts: True
    bio: |
      Sondra spearheads the design process
      through user testing, brand development, and interface design.
      She has been creating custom brands
      and integrated web graphics for over eleven years.
      She has lead the marketing teams
      for a variety of small businesses,
      and acted as co-founder and Chief Marketing Officer
      of a personal care products manufacturing startup
      where she coordinated multiple crowdfunding campaigns
      that reached over 200% of their goal.
      Sondra is also a multi-media artist, author, and musician —
      bringing a unique perspective
      to audience engagement and interaction.
    links:
      - twitter: 'sondraeby'
        github: 'sondrae'
        dribbble: 'sondraeby'

  - name: 'Stacy Kvernmo'
    author: 'stacy'
    role: 'user-experience developer'
    adr:
      city: 'Chicago'
      state: 'IL'
    no_posts: True
    bio: |
      Stacy takes the lead on interface development,
      architecting accessible and maintainable
      HTML, CSS, and Sass that users will interact with directly
      across different browsers and devices.
      Balancing her love of design and code,
      She is constantly experimenting with new front-end web techniques,
      creating efficient workflows,
      increasing performance,
      and contributing to open source projects.
      She has presented for many
      front-end conferences and podcasts,
      and also enjoys teaching and writing
      about design and development.
    links:
      - twitter: 'stacykvernmo'
        github: 'stacyk'
        lanyrd: 'stacy'

  - name: 'David Glick'
    author: 'david'
    role: 'server-side developer'
    adr:
      city: 'Seattle'
      state: 'WA'
    no_posts: True
    bio: |
      David is co-leads our server-side development,
      managing code architecture,
      database design,
      and deployment.
      He has been building
      web-based software in Python for over a decade.
      He has been an active contributor to
      the Plone web content management system,
      and a member of the Plone Framework and Security Teams.
    links:
      - twitter: 'davisagli'
        github: 'davisagli'
        lanyrd: 'davisagli'
        stackoverflow: '212493'

  - name: 'Kit La Touche'
    author: 'kit'
    role: 'server-side developer'
    adr:
      city: 'Boulder'
      state: 'CO'
    no_posts: True
    bio: |
      Kit co-leads our server-side development,
      managing code architecture,
      database design,
      and deployment.
      He is a web developer,
      computational linguist,
      Linux system administrator,
      and game designer.
      He’s been active in
      Python & Django web development since 2007,
      and also acts as a process consultant for businesses —
      helping teams find the flow of communication
      that works best for them.
    links:
      - twitter: 'wlonk'
        github: 'wlonk'

birds_former:
  - name: 'Claudina Sarahe'
    url: 'https://twitter.com/itsmisscs'
  - name: 'Rachel Nabors'
    url: 'https://twitter.com/rachelnabors'
  - name: 'Una Kravets'
    url: 'https://twitter.com/Una'


# Navigation
# ----------

nav:
  - text: 'home'
    url: '/'
  - text: 'birds'
    url: '/birds/'
  - text: 'work'
    url: '/work/'
  - text: 'blog'
    url: '/blogtemplate/'
  - text: 'community'
    url: '/community/'
  - text: 'contact'
    url: '/contact/'



# Site Settings
# -------------

copyright: '2009–2016'
author: 'oddbird'
comments: false
location: 'blog'
email: 'birds@oddbird.net'



# rstBlog Setup
# -------------

active_modules: [
  pygments_simple,
  tags,
  blog,
  author,
  wrap,
  typogrify,
  hashedassets
  ]
canonical_url: http://oddbird.net/
template_path: ../templates
asset_map_path: static/dist/assets.json
rst_writer: html5writer
ignore_files: ['.*', '_*', 'config*.yml', 'Makefile', 'README', '*.conf', '*~']
modules:
  pygments:
    style: tango
  blog:
    index_url: /blog/
    per_page: 10



# Past Talks
# ----------

talks_past:

  - title: 'Magic with Sass Maps'
    author: 'miriam'
    date: ['09', '12', '2014']
    venue: 'BlendConf'
    url: 'http://www.blendconf.com/'

  - title: 'Getting to know Sass'
    author: 'claudina'
    date: ['09', '11', '2014']
    venue: 'BlendConf'
    url: 'http://www.blendconf.com/'

  - title: 'The Post-Obsolete Book'
    author: 'miriam'
    date: ['06', '19', '2014']
    venue: 'ELO Conference'
    url: 'http://conference.eliterature.org/'

  - title: 'Sass Bites #37'
    author: 'claudina'
    date: ['05', '13', '2014']
    video: 'https://www.youtube.com/watch?v=BtWaFDpyDCI'
    venue: 'Sass Bites'
    url: 'https://www.youtube.com/user/sassbites'

  - title: 'Your Own Damn [Susy] System'
    author: 'miriam'
    date: ['04', '24', '2014']
    slides: 'http://miriamsuzanne.com/pres/susy2/'
    video: 'http://vimeo.com/miriamsuzanne/susy-2-system'
    venue: 'Bmore Sass'
    url: 'http://bmore-sass.com/'

  - title: 'Show Your Work <i>&</i> Share Your Toys'
    author: 'miriam'
    date: ['04', '19', '2014']
    slides: 'http://miriamsuzanne.com/pres/show-yr-work/index.html'
    venue: 'Camp Sass'
    url: 'http://campsass.com/2014/'

  - title: 'Set Your Code Free'
    author: 'carl'
    date: ['04', '13', '2014']
    slides: 'http://oddbird.net/set-your-code-free-preso/'
    video: 'http://pyvideo.org/video/2637/set-your-code-free-releasing-and-maintaining-an'
    venue: 'PyCon'
    url: 'https://us.pycon.org/2014/'

  - title: 'Susy Grids 2.0'
    author: 'miriam'
    date: ['03', '13', '2014']
    video: 'https://www.youtube.com/watch?v=m7k-vBzebPg'
    venue: 'Sass Bites'
    url: 'https://www.youtube.com/user/sassbites'

  - title: 'Python Testing Tools'
    author: 'carl'
    date: ['02', '28', '2014']
    slides: 'http://oddbird.net/python-testing-tools-preso/'
    venue: 'ConFoo'
    url: 'http://confoo.ca/'

  - title: 'Advanced Python'
    author: 'carl'
    date: ['02', '27', '2014']
    slides: 'http://oddbird.net/advanced-python-preso/'
    venue: 'ConFoo'
    url: 'http://confoo.ca/'

  - title: 'Organizing Sass Partials'
    author: 'miriam'
    date: ['11', '19', '2013']
    slides: 'http://miriamsuzanne.com/pres/sass-partials/'
    venue: 'NYCSass Meetup'
    url: 'http://www.meetup.com/nyc-sass/events/146898452/'

  - title: 'Show Your Work <i>&</i> Share Your Toys'
    author: 'miriam'
    date: ['10', '12', '2013']
    slides: 'http://miriamsuzanne.com/pres/show-yr-work/index.html'
    video: 'https://vimeo.com/channels/sassconf2013/86306775'
    venue: 'SassConf'
    url: 'http://sassconf.com/2013/'

  - title: 'Getting Started with Automated Testing'
    author: 'carl'
    date: ['03', '16', '2013']
    slides: 'http://oddbird.net/start-testing-preso/'
    video: 'http://pyvideo.org/video/1674/getting-started-with-automated-testing'
    venue: 'PyCon'
    url: 'https://us.pycon.org/2013/'
